### ISSUE TITLE
Also generate Schrute bucks

### ISSUE THREAD

**Issue by soberstadt** [CruGlobal/bill-bucks-generator#6]
https://theoffice.fandom.com/wiki/Schrute_Buck

**Comment by JasonBuckner** [comment]
I've always been partial to [Stanley Nickels](https://theoffice.fandom.com/wiki/Stanley_Nickel).

**Comment by soberstadt** [comment]
@JasonBuckner I appreciate the feedback. Do you have a suggestion on how we can mint a Stanley Nickle?

**Comment by JasonBuckner** [comment]
[http://www.custompogs.com/](http://www.custompogs.com/) , of course!
But hopefully, you're not being serious about either the Schrute Buck or the Stanley Nickel, as either would (I feel) dilute the ethos of the Bill Bucks program. 
If your aim is merely to toy with providing alternative currencies, it may interest you to know that since 2017, US Fund Development has been using a version of Bill Bucks too. Their system is structured very differently than ours, but they're using Bills that I designed. Jesus Film Project also approached us in June asking to use Bill Bucks too. I don't know what they implemented, if anything. I think we were still figuring out how to do Digital Bill Bucks at the time and THIS too will be a "game changer" once it's publicized. 
Don't want to shoot down the idea; just food for thought.

**Comment by soberstadt** [comment]
That's a good word. I was slightly serious, but perhaps if Schrute Bucks were added to this app we would hide it so most people don't see it. The reality is that we probably want to push people to actually give out bills, so it might be a distraction at best.

**Comment by JasonBuckner** [comment]
Closing for now as "won't do".
